const STATUS_COLORS={unassigned:'#888888',royaume:'#163d73',allie:'#2d7a48',neutre:'#b1aa9b',hostile:'#8c1c2c',revendique:'#c9a227'};
const saved=()=>JSON.parse(localStorage.getItem('uk2308_territories')||'{}');let territoryData=saved();let geoLayer;let currentFilter='all';
const map=L.map('world-map',{minZoom:2,maxZoom:7,worldCopyJump:true,zoomControl:true}).setView([25,5],2);
function featureId(f){return f.properties.iso_3166_2||f.properties.adm1_code||f.properties.gn_id||`${f.properties.adm0_a3||f.properties.admin||'UNK'}-${f.properties.name||f.properties.name_en||'region'}`.replace(/\s+/g,'-')}
function statusOf(f){return territoryData[featureId(f)]?.status||'unassigned'}
function style(f){const s=statusOf(f);return{color:'#373737',weight:.65,fillColor:STATUS_COLORS[s],fillOpacity:currentFilter==='all'||currentFilter===s?.82:.08}}
function selectFeature(f,l){const id=featureId(f),custom=territoryData[id]||{},name=custom.displayName||f.properties.name||f.properties.name_en||'Territoire',country=f.properties.admin||f.properties.geonunit||'';document.getElementById('map-info').innerHTML=`<p class="kicker">IDENTIFIANT : ${id}</p><h2>${name}</h2><p><strong>${country}</strong></p><p>Statut : ${custom.status||'non attribué'}</p><p>${custom.note||'Aucune note diplomatique.'}</p>`;l.setStyle({weight:2.5,color:'#fff'});}
fetch('https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_1_states_provinces.geojson').then(r=>{if(!r.ok)throw Error('Erreur réseau');return r.json()}).then(data=>{geoLayer=L.geoJSON(data,{style,onEachFeature:(f,l)=>{l.bindTooltip(`${f.properties.name||''}<br><em>${f.properties.admin||''}</em>`,{sticky:true});l.on('click',()=>selectFeature(f,l));}}).addTo(map);document.getElementById('map-loading').remove();}).catch(()=>{document.getElementById('map-loading').textContent='La carte ne peut pas être chargée. Vérifiez votre connexion internet.'});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;geoLayer?.setStyle(style)}));
document.getElementById('map-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(!q||!geoLayer)return;let found;geoLayer.eachLayer(l=>{const f=l.feature,p=f.properties;if(!found&&`${p.name||''} ${p.admin||''}`.toLowerCase().includes(q))found=l});if(found){map.fitBounds(found.getBounds(),{maxZoom:5});selectFeature(found.feature,found)}});window.addEventListener('storage',()=>{territoryData=saved();geoLayer?.setStyle(style)});